companies_name = ["AT&T Inc.",
"Advanced Micro Devices, Inc.",
"Alphabet Inc.",
"Alphabet Inc.",
"Amazon.com, Inc.",
"Apple Inc.",
"Aston Martin Lagonda Global Holdings plc",
"BNP Paribas SA",
"Banco Bilbao Vizcaya Argentaria, S.A.",
"Banco Santander (Brasil) S.A.",
"Bank of America Corporation",
"Bank of Montreal",
"Berkshire Hathaway Inc.",
"Bitcoin USD",
"Chevron Corporation",
"Citigroup Inc.",
"Exxon Mobil Corporation",
"Ford Motor Company",
"HDFC Bank Limited",
"HSBC Holdings plc",
"ICICI Bank Limited",
"ING Groep N.V.",
"Industrial and Commercial Bank of China Limited",
"Intel Corporation",
"Interactive Brokers Group, Inc.",
"Intesa Sanpaolo S.p.A.",
"Itaú Unibanco Holding S.A.",
"JPMorgan Chase & Co.",
"Johnson & Johnson",
"Linde plc",
"McDonald's Corporation",
"Meta Platforms, Inc.",
"Microsoft Corporation",
"Morgan Stanley",
"NVIDIA Corporation",
"National Australia Bank Limited",
"Netflix, Inc.",
"Nordea Bank Abp",
"Oracle Corporation", 
"PepsiCo, Inc.",
"Pfizer Inc.",
"Piedmont Lithium Inc.",
"Realty Income Corporation",
"Royal Bank of Canada",
"Saudi Arabian Oil Company",
"Starbucks Corporation",
"Sumitomo Mitsui Financial Group, Inc.",
"Taiwan Semiconductor Manufacturing Company Limited",
"Tesla, Inc.",
"The Bank of Nova Scotia",
"The Charles Schwab Corporation",
"The Coca-Cola Company",
"The Goldman Sachs Group, Inc.",
"The Home Depot, Inc.",
"The PNC Financial Services Group, Inc.",
"The Procter & Gamble Company",
"The Toronto-Dominion Bank",
"The Walt Disney Company",
"Toyota Motor Corporation",
"Truist Financial Corporation",
"U.S. Bancorp",
"UBS Group AG",
"UnitedHealth Group Incorporated",
"Verizon Communications Inc.",
"Walmart Inc.",
"Warner Bros. Discovery, Inc.",
"Wells Fargo & Company",
"Wells Fargo & Company"
]

companies_info = [["AT&T Inc.","T"],
["Advanced Micro Devices, Inc.","AMD"],
["Alphabet Inc.","GOOG"],
["Alphabet Inc.","GOOGL"],
["Amazon.com, Inc.","AMZN"],
["Apple Inc.","AAPL"],
["Aston Martin Lagonda Global Holdings plc","AML.L"],
["BNP Paribas SA","BNPQY"],
["Banco Bilbao Vizcaya Argentaria, S.A.","BBVA"],
["Banco Santander (Brasil) S.A.","BSBR"],
["Bank of America Corporation","BAC"],
["Bank of Montreal","BMO"],
["Berkshire Hathaway Inc.","BRK-B"],
["Bitcoin USD","BTC-USD"],
["Chevron Corporation","CVX"],
["Citigroup Inc.","C"],
["Exxon Mobil Corporation","XOM"],
["Ford Motor Company","F"],
["HDFC Bank Limited","HDB"],
["HSBC Holdings plc","HSBC"],
["ICICI Bank Limited","IBN"],
["ING Groep N.V.","ING"],
["Industrial and Commercial Bank of China Limited","IDCBY"],
["Intel Corporation","INTC"],
["Interactive Brokers Group, Inc.","IBKR"],
["Intesa Sanpaolo S.p.A.","ISNPY"],
["Itaú Unibanco Holding S.A.","ITUB"],
["JPMorgan Chase & Co.","JPM"],
["Johnson & Johnson","JNJ"],
["Linde plc","LIN"],
["McDonald's Corporation","MCD"],
["Meta Platforms, Inc.","META"],
["Microsoft Corporation","MSFT"],
["Morgan Stanley","MS"],
["NVIDIA Corporation","NVDA"],
["National Australia Bank Limited","NABZY"],
["Netflix, Inc.","NFLX"],
["Nordea Bank Abp","NRDBY"],
["Oracle Corporation","ORCL"],
["PepsiCo, Inc.","PEP"],
["Pfizer Inc.","PFE"],
["Piedmont Lithium Inc.","PLL"],
["Realty Income Corporation","O"],
["Royal Bank of Canada","RY"],
["Saudi Arabian Oil Company","2222.SR"],
["Starbucks Corporation","SBUX"],
["Sumitomo Mitsui Financial Group, Inc.","SMFG"],
["Taiwan Semiconductor Manufacturing Company Limited","TSM"],
["Tesla, Inc.","TSLA"],
["The Bank of Nova Scotia","BNS"],
["The Charles Schwab Corporation","SCHW"],
["The Coca-Cola Company","KO"],
["The Goldman Sachs Group, Inc.","GS"],
["The Home Depot, Inc.","HD"],
["The PNC Financial Services Group, Inc.","PNC"],
["The Procter & Gamble Company","PG"],
["The Toronto-Dominion Bank","TD"],
["The Walt Disney Company","DIS"],
["Toyota Motor Corporation","TM"],
["Truist Financial Corporation","TFC"],
["U.S. Bancorp","USB"],
["UBS Group AG","UBS"],
["UnitedHealth Group Incorporated","UNH"],
["Verizon Communications Inc.","VZ"],
["Walmart Inc.","WMT"],
["Warner Bros. Discovery, Inc.","WBD"],
["Wells Fargo & Company","WFC"],
["Wells Fargo & Company","WFC-PQ"]
]

max_gain = [[0,""],[0,""],[0,""]]

max_lost = [[0,""],[0,""],[0,""]]

