companies_name = ["Apple Inc.",
"Advanced Micro Devices, Inc.",
"Amazon.com, Inc.",
"Bank of America Corporation",
"Banco Bilbao Vizcaya Argentaria, S.A.",
"Bank of Montreal",
"BNP Paribas SA",
"The Bank of Nova Scotia",
"Berkshire Hathaway Inc.",
"Banco Santander (Brasil) S.A.",
"Citigroup Inc.",
"Chevron Corporation",
"The Walt Disney Company",
"Ford Motor Company",
"Alphabet Inc.",
"Alphabet Inc.",
"The Goldman Sachs Group, Inc.",
"The Home Depot, Inc.",
"HDFC Bank Limited",
"HSBC Holdings plc",
"Interactive Brokers Group, Inc.",
"ICICI Bank Limited",
"Industrial and Commercial Bank of China Limited",
"ING Groep N.V.",
"Intel Corporation",
"Intesa Sanpaolo S.p.A.",
"Itaú Unibanco Holding S.A.",
"Johnson & Johnson",
"JPMorgan Chase & Co.",
"The Coca-Cola Company",
"McDonald's Corporation",
"Meta Platforms, Inc.",
"Morgan Stanley",
"Microsoft Corporation",
"National Australia Bank Limited",
"Netflix, Inc.",
"Nordea Bank Abp",
"NVIDIA Corporation",
"Realty Income Corporation",
"PepsiCo, Inc.",
"Pfizer Inc.",
"The Procter & Gamble Company",
"The PNC Financial Services Group, Inc.",
"Royal Bank of Canada",
"Starbucks Corporation",
"The Charles Schwab Corporation",
"Sumitomo Mitsui Financial Group, Inc.",
"AT&T Inc.",
"The Toronto-Dominion Bank",
"Truist Financial Corporation",
"Tesla, Inc.",
"UBS Group AG",
"UnitedHealth Group Incorporated",
"U.S. Bancorp",
"Verizon Communications Inc.",
"Wells Fargo & Company",
"Wells Fargo & Company",
"Walmart Inc.",
"Exxon Mobil Corporation"]

companies_info = [["Apple Inc.","AAPL"],
["Advanced Micro Devices, Inc.","AMD"],
["Amazon.com, Inc.","AMZN"],
["Bank of America Corporation","BAC"],
["Banco Bilbao Vizcaya Argentaria, S.A.","BBVA"],
["Bank of Montreal","BMO"],
["BNP Paribas SA","BNPQY"],
["The Bank of Nova Scotia","BNS"],
["Berkshire Hathaway Inc.","BRK-B"],
["Banco Santander (Brasil) S.A.","BSBR"],
["Citigroup Inc.","C"],
["Chevron Corporation","CVX"],
["The Walt Disney Company","DIS"],
["Ford Motor Company","F"],
["Alphabet Inc.","GOOG"],
["Alphabet Inc.","GOOGL"],
["The Goldman Sachs Group, Inc.","GS"],
["The Home Depot, Inc.","HD"],
["HDFC Bank Limited","HDB"],
["HSBC Holdings plc","HSBC"],
["Interactive Brokers Group, Inc.","IBKR"],
["ICICI Bank Limited","IBN"],
["Industrial and Commercial Bank of China Limited","IDCBY"],
["ING Groep N.V.","ING"],
["Intel Corporation","INTC"],
["Intesa Sanpaolo S.p.A.","ISNPY"],
["Itaú Unibanco Holding S.A.","ITUB"],
["Johnson & Johnson","JNJ"],
["JPMorgan Chase & Co.","JPM"],
["The Coca-Cola Company","KO"],
["McDonald's Corporation","MCD"],
["Meta Platforms, Inc.","META"],
["Morgan Stanley","MS"],
["Microsoft Corporation","MSFT"],
["National Australia Bank Limited","NABZY"],
["Netflix, Inc.","NFLX"],
["Nordea Bank Abp","NRDBY"],
["NVIDIA Corporation","NVDA"],
["Realty Income Corporation","O"],
["PepsiCo, Inc.","PEP"],
["Pfizer Inc.","PFE"],
["The Procter & Gamble Company","PG"],
["The PNC Financial Services Group, Inc.","PNC"],
["Royal Bank of Canada","RY"],
["Starbucks Corporation","SBUX"],
["The Charles Schwab Corporation","SCHW"],
["Sumitomo Mitsui Financial Group, Inc.","SMFG"],
["AT&T Inc.","T"],
["The Toronto-Dominion Bank","TD"],
["Truist Financial Corporation","TFC"],
["Tesla, Inc.","TSLA"],
["UBS Group AG","UBS"],
["UnitedHealth Group Incorporated","UNH"],
["U.S. Bancorp","USB"],
["Verizon Communications Inc.","VZ"],
["Wells Fargo & Company","WFC"],
["Wells Fargo & Company","WFC-PQ"],
["Walmart Inc.","WMT"],
["Exxon Mobil Corporation","XOM"]]

historical_data = []

company_data = ["","",""]

max_gain = [[0,""],[0,""],[0,""]]

max_lost = [[0,""],[0,""],[0,""]]

